var list = [
  {id:1,title:'one',source:'1.mp3',group:1},
  {id:2,title:'two',source:'2.mp3',group:1},
  {id:3,title:'three',source:'3.mp3',group:1},
];


var group1 = [
  'ROCK IT DOWN',
  'around the world',
  'over drive',
  'Rage your dream',
  'BREAK IN2 THE NITE',
  'platinum',
  'Blazin\' Beat',
  'words of the mind 〜brandnew journey〜',
  'sweet vibration',
  'Gamble Rumble',
  'SUPER SONIC DANCE',
  'FLY ME SO HIGH',
  'come together(RADIO EDIT)',
  'Romancing Train',
  'FUTURE BREEZE',
  '¡WAKE YOUR LOVE!',
  'BURNING DANCE',
  'Painless PAIN',
  'Blast My Desire',
  'DOGFIGHT',
  'GHETTO BLASTER',
  'How To See You Again',
  'Noizy Tribe',
  'FREAKY PLANET',
  'DISCO TIME',
  '雷鳴-out of kontrol-',
  'Angel Eyes',
  'Systematic Fantasy',
  'Good Day Good Time',
  'SPEED MASTER',
  'DIVE INTO STREAM',
  'Fate Seeker',
  'oveRtaKerS feat.RYUICHI KAWAMURA × SUGIZO',
  'Raise Up',
  '夕愁想花',
  'Outsoar The Rainbow'
];
