var ASSETS = {
  sound: {
    'ROCK IT DOWN' : 'sound/ROCK IT DOWN.mp3',
    'around the world' : 'sound/around the world.mp3',
    'over drive' : 'sound/over drive.mp3',
    'Rage your dream' : 'sound/Rage your dream.mp3',
    'BREAK IN2 THE NITE' : 'sound/BREAK IN2 THE NITE.mp3',
    'platinum' : 'sound/platinum.mp3',
    'Blazin\' Beat' : 'sound/Blazin\' Beat.mp3',
    'words of the mind 〜brandnew journey〜' : 'sound/words of the mind 〜brandnew journey〜.mp3',
    'sweet vibration' : 'sound/sweet vibration.mp3',
    'Gamble Rumble' : 'sound/Gamble Rumble.mp3',
    'SUPER SONIC DANCE' : 'sound/SUPER SONIC DANCE.mp3',
    'FLY ME SO HIGH' : 'sound/FLY ME SO HIGH.mp3',
    'come together(RADIO EDIT)' : 'sound/come together(RADIO EDIT).mp3',
    'Romancing Train' : 'sound/Romancing Train.mp3',
    'FUTURE BREEZE' : 'sound/FUTURE BREEZE.mp3',
    '¡WAKE YOUR LOVE!' : 'sound/¡WAKE YOUR LOVE!.mp3',
    'BURNING DANCE' : 'sound/BURNING DANCE.mp3',
    'Painless PAIN' : 'sound/Painless PAIN.mp3',
    'Blast My Desire' : 'sound/Blast My Desire.mp3',
    'DOGFIGHT' : 'sound/DOGFIGHT.mp3',
    'GHETTO BLASTER' : 'sound/GHETTO BLASTER.mp3',
    'How To See You Again' : 'sound/How To See You Again.mp3',
    'Noizy Tribe' : 'sound/Noizy Tribe.mp3',
    'FREAKY PLANET' : 'sound/FREAKY PLANET.mp3',
    'DISCO TIME' : 'sound/DISCO TIME.mp3',
    '雷鳴-out of kontrol-' : 'sound/雷鳴-out of kontrol-.mp3',
    'Angel Eyes' : 'sound/Angel Eyes.mp3',
    'Systematic Fantasy' : 'sound/Systematic Fantasy.mp3',
    'Good Day Good Time' : 'sound/Good Day Good Time.mp3',
    'SPEED MASTER' : 'sound/SPEED MASTER.mp3',
    'DIVE INTO STREAM' : 'sound/DIVE INTO STREAM.mp3',
    'Fate Seeker' : 'sound/Fate Seeker.mp3',
    'oveRtaKerS feat.RYUICHI KAWAMURA × SUGIZO' : 'sound/oveRtaKerS feat.RYUICHI KAWAMURA × SUGIZO.mp3',
    'Raise Up' : 'sound/Raise Up.mp3',
    '夕愁想花' : 'sound/夕愁想花.mp3',
    'Outsoar The Rainbow' : 'sound/Outsoar The Rainbow.mp3',
  }
}

var group1 = [
  'ROCK IT DOWN',
  'around the world',
  'over drive',
  'Rage your dream',
  'BREAK IN2 THE NITE',
  'platinum',
  'Blazin\' Beat',
  'words of the mind 〜brandnew journey〜',
  'sweet vibration',
  'Gamble Rumble',
  'SUPER SONIC DANCE',
  'FLY ME SO HIGH',
  'come together(RADIO EDIT)',
  'Romancing Train',
  'FUTURE BREEZE',
  '¡WAKE YOUR LOVE!',
  'BURNING DANCE',
  'Painless PAIN',
  'Blast My Desire',
  'DOGFIGHT',
  'GHETTO BLASTER',
  'How To See You Again',
  'Noizy Tribe',
  'FREAKY PLANET',
  'DISCO TIME',
  '雷鳴-out of kontrol-',
  'Angel Eyes',
  'Systematic Fantasy',
  'Good Day Good Time',
  'SPEED MASTER',
  'DIVE INTO STREAM',
  'Fate Seeker',
  'oveRtaKerS feat.RYUICHI KAWAMURA × SUGIZO',
  'Raise Up',
  '夕愁想花',
  'Outsoar The Rainbow'
];
